[functions]
directory = "functions/"

[build]
command = """
mkdir functions &&
cargo build --release --bin pokemon-api &&
cp target/release/pokemon-api functions/
"""
publish = "crates"

[[redirects]]
from = "/api/pokemon/:slug"
to = "/.netlify/functions/pokemon"
status = 200
